
--테이블명 CUSTOMER 
create table customer(
CUSTOMER_ID NUMBER(10,0) PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(100) NOT NULL,
CUSTOMER_EMAIL VARCHAR2(100) CONSTRAINT CTR_E UNIQUE,
CUSTOMER_PHONE VARCHAR2(20) ,
CUSTOMER_ADDRESS VARCHAR2(255),
CONSTRAINT CTR_P UNIQUE(CUSTOMER_PHONE)
);
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_ID IS'고객아이디';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_NAME IS'고객이름';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_EMAIL IS'고객이메일';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_PHONE IS'고객핸드폰번호';
COMMENT ON COLUMN "CUSTOMER".CUSTOMER_ADDRESS IS'고객주소';

COMMIT;

--PRODUcT 테이블생성
CREATE TABLE PRODUCT_CAFE (
PRODUCT_ID NUMBER(10,0) PRIMARY KEY,
PRODUCT_NAME VARCHAR2(100) NOT NULL,
PRODUCT_PRICAE NUMBER(10,2)NOT NULL,
PRODUCT_DESC VARCHAR2(200) CONSTRAINT PRO_D UNIQUE
);

INSERT INTO PRODUCT_CAFE 
VALUES (1,'아메리카노',3000,'신선한 원두로만든 아메리카노');

INSERT INTO PRODUCT_CAFE 
VALUES (2,'카페라떼',3500,'부드러운 우유가 들어간 라떼');

INSERT INTO PRODUCT_CAFE 
VALUES (3,'카푸치노',4000,'진한 커피와 거품이 어우러진 카푸치노');

INSERT INTO PRODUCT_CAFE 
VALUES (4,'마끼아또',4500,'달콤한 시럽이 들어간 마끼아또');









CREATE TABLE FOOD_COMPANY(
    COMPANY_ID NUMBER(10,0) PRIMARY kEY,
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    COMPANY_ADDRESS VARCHAR2(255),
    COMPANY_PHONE VARCHAR2(20)
);

CREATE TABLE SNACKS1(
SNACK_ID NUMBER(10,0) PRIMARY KEY,
SNACK_NAME VARcHAR2(100) NOT NULL ,
PRICE NUMBER (10,2) NOT NULL,
CCCCCCCCCC NUMBER(10,0),

CONSTRAINT FK_COMPANY1 FOREIGN KEY (CCCCCCCCCC)
REFERENCES FOOD_COMPANY (COMPANY_ID)
ON DELETE CASCADE


);

CREATE TABLE SNACKS2(
SNACK_ID NUMBER(10,0) PRIMARY KEY,
SNACK_NAME VARcHAR2(100) NOT NULL ,
PRICE NUMBER (10,2) NOT NULL,
AAAAAAAAAAA NUMBER(10,0),

CONSTRAINT FK_COMPANY2 FOREIGN KEY (AAAAAAAAAAA)
REFERENCES FOOD_COMPANY (COMPANY_ID)
ON DELETE CASCADE

);

CREATE TABLE DRINK_COMPANY(
DRINK_ID NUMBER(10,0) PRIMARY KEY,
DRINK_NAME VARCHAR2(100) NOT NULL,
DRINK_ADDRESS VARCHAR2(255),
DRINK_PHONE VARCHAR2(20)

);

CREATE TABLE SOFTS(
SOFTS_ID NUMBER(10,0)PRIMARY KEY,
SOFTS_NAME VARCHAR2(100) NOT NULL,
PRICE NUMBER(10,2) NOT NULL,

COMPANY1_ID NUMBER (10,0),

CONSTRAINT DRINK_COMPANY FOREIGN KEY (COMPANY1_ID)
REFERENCES DRINK_COMPANY (DRINK_ID)
ON DELETE CASCADE

);

INSERT INTO DRINK_COMPANY
VALUES (1,'코카콜라','서울시','02-1111-1111');

INSERT INTO DRINK_COMPANY
VALUES (2,'펩시제로라임','서울시 강남','02-2222-2222');

INSERT INTO SOFTS 
VALUES (1,'콜라',1500,1);

INSERT INTO SOFTS 
VALUES (2,'사이다',1200,1);

INSERT INTO SOFTS 
VALUES (3,'펩시콜라',1000,2);

INSERT INTO SOFTS 
VALUES (4,'마운틴듀',2000,2);






























